version: '2'

services:
  backend:
    
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    env_file: 
      - .env
        
    command: ["./activate.sh"]

  # frontend:



  
  # subscriber:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile

  #   env_file: 
  #     - .env
    
  #   volumes:
  #     - './mydarknet:/api/mydarknet'
    

  #   restart: "on-failure"

  #   command: python subscriber.py
    
  